name: Weekly activity report

on:
  schedule:
    - cron: '0 12 * * 1'
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: create service-secrets.json
        run: |
          echo "$SERVICE_SECRETS" > service-secrets.json
        env:
          SERVICE_SECRETS: ${{ secrets.SERVICE_SECRETS }}
      - name: Install dependencies
        run: |
          uv sync

      - name: Build the dashboard
        run: |
          uv run traceback-with-variables napari_dashboard.get_weekly_summary --send-zulip --channel ${{ (github.event_name == 'schedule') && 'core-devs' || '"metrics and analytics"' }}
        env:
          PEPY_KEY: ${{ secrets.PEPY_KEY }}
          GH_TOKEN_: ${{ secrets.GITHUB_TOKEN }}
          ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
